# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8492846cae2bfab30634f64aaf3730691b1e4d75ded5de4740d05ac98fc94b5099379961ca3a98886eddbf325754c81277e7afe8d2a62c8e8633be8bf53a9ed5

test:
  secret_key_base: 90ee94f619ba16ee0e27bec21c87238856239ba158fc56fbbd71e297da043541e29756d271db36cb9233a7fc9f83cd7399b930a2c27c7886a30c51a05f81385d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
